title: "antoine.studio"
description: "documentation"
main_url: "https://antoine.studio"
introduction: "This space is being updated, after a far too long pause ✄ This website ☼ is my digital studio, a place where I can experiment without ⁂ constraints. It's also my personal assistant, it helps me when I'm not sure how to do ✿ something I've done before. It invites me to write (and then find) my personal knowledge ⧉ online. Welcome&nbsp;✺"
navigation:
  "antoine.studio": "index"
  "content": "content"
  "flux": "flux"
  "about": "about"
flux:
  visibility: True
  title: "flux"
  slug: "flux"
footer: "antoine.studio ☼&nbsp;2022 — [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) — [RSS Feed](https://antoine.studio/rss.xml)"